import type { Metadata } from 'next'
import '@/app/css/globals.css'

export const metadata: Metadata = {
  title: "Portfolio- Shivansha Pathak",
  description: "Generated by Next.js",
  icons: {
    icon: "" , 
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
